### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by mroberts1** [hellerve/blog#144]
Hi, I came across your blog and like the simple design! Can you provide any information on how to use your setup, or is this just for personal use? I have Python 3.9 installed but am not sure how to generate or publish posts.

**Comment by hellerve** [comment]
Hey @mroberts1, thanks for your interest! I think you also wrote an email to me, so let’s continue the conversation over there.

I’ll close this issue for now, feel free to reopen it if you think that’s a mistake.
